services:
  router1:
    build: .
    container_name: my-rip-router1
    environment:
      - ROUTER_ID=1
    command: ["./peer-listen", "router", "1"]
    stdin_open: true
    tty: true
    networks:
      custom-net-6:
        ipv4_address: 192.168.60.20
      custom-net-1:
        ipv4_address: 192.168.10.10

  router2:
    build: .
    container_name: my-rip-router2
    environment:
      - ROUTER_ID=2
    command: ["./peer-listen", "router", "2"]
    stdin_open: true
    tty: true
    networks:
      custom-net-1:
        ipv4_address: 192.168.10.20
      custom-net-2:
        ipv4_address: 192.168.20.10

  router3:
    build: .
    container_name: my-rip-router3
    environment:
      - ROUTER_ID=3
    command: ["./peer-listen", "router", "3"]
    stdin_open: true
    tty: true
    networks:
      custom-net-2:
        ipv4_address: 192.168.20.20
      custom-net-3:
        ipv4_address: 192.168.30.10

  router4:
    build: .
    container_name: my-rip-router4
    environment:
      - ROUTER_ID=4
    command: ["./peer-listen", "router", "4"]
    stdin_open: true
    tty: true
    networks:
      custom-net-3:
        ipv4_address: 192.168.30.20
      custom-net-4:
        ipv4_address: 192.168.40.10

  router5:
    build: .
    container_name: my-rip-router5
    environment:
      - ROUTER_ID=5
    command: ["./peer-listen", "router", "5"]
    stdin_open: true
    tty: true
    networks:
      custom-net-4:
        ipv4_address: 192.168.40.20
      custom-net-5:
        ipv4_address: 192.168.50.10

  router6:
    build: .
    container_name: my-rip-router6
    environment:
      - ROUTER_ID=6
    command: ["./peer-listen", "router", "6"]
    stdin_open: true
    tty: true
    networks:
      custom-net-5:
        ipv4_address: 192.168.50.20
      custom-net-6:
        ipv4_address: 192.168.60.10

  topology-grapher:
    build: .
    container_name: topology-grapher1
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
    command: ["./topology-grapher"]
    stdin_open: true
    tty: true
    depends_on:
      - router1
      - router2

networks:
  custom-net-1:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.10.0/24"

  custom-net-2:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.20.0/24"

  custom-net-3:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.30.0/24"

  custom-net-4:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.40.0/24"

  custom-net-5:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.50.0/24"

  custom-net-6:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.60.0/24"
      
